/* Generated By:JavaCC: Do not edit this line. OCMParserTreeConstants.java Version 4.1d1 */
package com.kissintellignetsystems.ocm.compiler.parser;

public interface OCMParserTreeConstants
{
  public int JJTOCMSPEC = 0;
  public int JJTCOLUMNFAMILY = 1;
  public int JJTFIELD = 2;
  public int JJTSUPERFAMILY = 3;
  public int JJTDYNAMICSUPERFAMILY = 4;
  public int JJTMANY2MANY = 5;


  public String[] jjtNodeName = {
    "OCMSpec",
    "ColumnFamily",
    "Field",
    "SuperFamily",
    "DynamicSuperFamily",
    "Many2Many",
  };
}
/* JavaCC - OriginalChecksum=545e099104c8905ece3296922149d5d2 (do not edit this line) */
