/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using Thrift;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Hadoop.Hbase.Thrift
{
  public class BatchMutation 
  {
    public byte[] row;
    public List<Mutation> mutations;

    public Isset __isset;
    public struct Isset {
      public bool row;
      public bool mutations;
    }

    public BatchMutation() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      TStruct struc = iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.row = iprot.ReadBinary();
              this.__isset.row = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                this.mutations = new List<Mutation>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  Mutation _elem2 = new Mutation();
                  _elem2 = new Mutation();
                  _elem2.Read(iprot);
                  this.mutations.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
              this.__isset.mutations = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BatchMutation");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.row != null) {
        field.Name = "row";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.row);
        oprot.WriteFieldEnd();
      }
      if (this.mutations != null) {
        field.Name = "mutations";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, this.mutations.Count));
          foreach (Mutation _iter3 in this.mutations)
          {
            _iter3.Write(oprot);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("BatchMutation(");
      sb.Append("row: ");
      sb.Append(this.row);
      sb.Append(",mutations: ");
      sb.Append(this.mutations);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
