/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using Thrift;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Hadoop.Hbase.Thrift
{
  public class TRegionInfo 
  {
    public byte[] startKey;
    public byte[] endKey;
    public long id;
    public byte[] name;
    public byte version;

    public Isset __isset;
    public struct Isset {
      public bool startKey;
      public bool endKey;
      public bool id;
      public bool name;
      public bool version;
    }

    public TRegionInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      TStruct struc = iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.startKey = iprot.ReadBinary();
              this.__isset.startKey = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.endKey = iprot.ReadBinary();
              this.__isset.endKey = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I64) {
              this.id = iprot.ReadI64();
              this.__isset.id = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              this.name = iprot.ReadBinary();
              this.__isset.name = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Byte) {
              this.version = iprot.ReadByte();
              this.__isset.version = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TRegionInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.startKey != null) {
        field.Name = "startKey";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.startKey);
        oprot.WriteFieldEnd();
      }
      if (this.endKey != null) {
        field.Name = "endKey";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.endKey);
        oprot.WriteFieldEnd();
      }
      field.Name = "id";
      field.Type = TType.I64;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(this.id);
      oprot.WriteFieldEnd();
      if (this.name != null) {
        field.Name = "name";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.name);
        oprot.WriteFieldEnd();
      }
      field.Name = "version";
      field.Type = TType.Byte;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      oprot.WriteByte(this.version);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TRegionInfo(");
      sb.Append("startKey: ");
      sb.Append(this.startKey);
      sb.Append(",endKey: ");
      sb.Append(this.endKey);
      sb.Append(",id: ");
      sb.Append(this.id);
      sb.Append(",name: ");
      sb.Append(this.name);
      sb.Append(",version: ");
      sb.Append(this.version);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
